try{
    throw ""

}catch(err){
    console.log(err)
}finally{

}